# Generated by Django 4.2 on 2025-10-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LESSON_VIEW', 'Lesson View'), ('LESSON_COMPLETE', 'Lesson Complete'), ('QUIZ_START', 'Quiz Start'), ('QUIZ_COMPLETE', 'Quiz Complete'), ('CHAT', 'Chat'), ('ENROLLMENT', 'Enrollment'), ('BADGE_EARNED', 'Badge Earned')], help_text='Type of activity', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object (course, lesson, etc.)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of the related object', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the quiz was completed', null=True)),
                ('score', models.PositiveIntegerField(default=0, help_text='Total points scored')),
                ('percentage', models.FloatField(default=0.0, help_text='Score as percentage (0-100)')),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('answers', models.JSONField(default=dict, help_text='JSON containing all answers submitted')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', 'timestamp'], name='analytics_u_user_id_471bcf_idx'),
        ),
    ]
