# Generated by Django 4.2 on 2025-10-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon class or image name', max_length=100)),
                ('badge_type', models.CharField(choices=[('ACHIEVEMENT', 'Achievement'), ('MILESTONE', 'Milestone'), ('SPECIAL', 'Special')], help_text='Type of badge', max_length=20)),
                ('requirement', models.JSONField(help_text='JSON containing conditions to earn this badge')),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Points awarded when badge is earned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField(help_text='Level number (1, 2, 3, etc.)', unique=True)),
                ('name', models.CharField(help_text='Level name (e.g., Beginner, Novice, etc.)', max_length=50)),
                ('xp_required', models.PositiveIntegerField(help_text='Total XP required to reach this level')),
                ('icon', models.CharField(help_text='Icon class or image name', max_length=100)),
                ('color', models.CharField(help_text='Color code for level badge', max_length=50)),
                ('rewards', models.JSONField(default=dict, help_text='JSON containing rewards for reaching this level')),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('COURSE_COMPLETION', 'Course Completion'), ('STREAK', 'Streak'), ('QUIZ_MASTER', 'Quiz Master'), ('SPEED_LEARNER', 'Speed Learner'), ('ENGAGEMENT', 'Engagement'), ('OTHER', 'Other')], help_text='Type of achievement', max_length=30)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned for this achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True, help_text='Whether to display this badge on profile')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ALL_TIME', 'All Time')], help_text='Leaderboard time period', max_length=10)),
                ('rank', models.PositiveIntegerField(help_text='User rank in this period')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total points in this period')),
                ('total_xp', models.PositiveIntegerField(default=0, help_text='Total XP in this period')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'rank'],
                'unique_together': {('user', 'period')},
            },
        ),
    ]
